### ISSUE TITLE
Cannot find reference 'load_json_dataset' in 'api.py' 

### ISSUE THREAD

**Issue by JennyLeePMH** [herrmannlab/dicomweb-client#72]
### Cannot find reference 'load_json_dataset' in 'api.py' 

Step to reproduce
- install dicomweb-client v0.57.1
- on a python IDE, import "load_json_dataset" following below instruction
![Loading Json Data to pydicom](https://user-images.githubusercontent.com/4551564/195917140-eff444cd-17e4-4e41-a87c-8b92a0bf3b57.png)
- got a error message: **Cannot find reference 'load_json_dataset' in 'api.py'**

**Comment by hackermd** [comment]
@JennyLeePMH thank you for your interest in the dicomweb-client library and for creating the issue.

This functionality has meanwhile been included into the pydicom library (see https://github.com/pydicom/pydicom/pull/862) and is available via [pydicom.dataset.Dataset.from_json()](https://pydicom.github.io/pydicom/dev/reference/generated/pydicom.dataset.Dataset.html#pydicom.dataset.Dataset.from_json).

The example should now look as follows:

```python
from pydicom import Dataset

metadata_datasets = [Dataset.from_json(ds) for ds in metadata]
```

I have updated the example in the documentation accordingly (see 04257537f399e1e89e894296f66f2214b2e39b25)
